[package]
name = "understory_examples"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
understory_responder = { path = "../understory_responder", features = [
  "box_tree_adapter",
  "std",
] }
kurbo = { workspace = true, default-features = true }
understory_box_tree = { path = "../understory_box_tree" }
understory_display = { path = "../understory_display" }
understory_display_vello = { path = "../understory_display_vello" }
understory_focus = { path = "../understory_focus" }
understory_index = { path = "../understory_index" }
ui-events = { workspace = true }
ui-events-winit = { workspace = true }
vello = { workspace = true, features = ["wgpu_default"] }
winit = { workspace = true }
pollster = "0.3"
